name = "discogs-mcp"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["global_fetch_strictly_public"]

[observability]
enabled = true

# Development environment (default)
[[kv_namespaces]]
binding = "MCP_LOGS"
id = "b0c83f4b63a94c7490a609095e35b84f"

[[kv_namespaces]]
binding = "MCP_RL"
id = "b4caaaa688cc45d2a9a85fe67ba53bfc"

[[kv_namespaces]]
binding = "MCP_SESSIONS"
id = "a0bc40f523d54a6ab70fa947ac3daeaf"

[[kv_namespaces]]
binding = "DISCOGS_OAUTH_CLIENTS"
id = "0fbf725469be4387b46582bdb195b4b7"

[[kv_namespaces]]
binding = "DISCOGS_OAUTH_TOKENS"
id = "a0829d327a6045ddbb724ec91b7f27ee"

# Production environment
[env.production]
name = "discogs-mcp-prod"

[[env.production.kv_namespaces]]
binding = "MCP_LOGS"
id = "768f383bd9a54f8c837decbaeb869b68"

[[env.production.kv_namespaces]]
binding = "MCP_RL"
id = "bfc831cedceb4a08a6d997909c3899ce"

[[env.production.kv_namespaces]]
binding = "MCP_SESSIONS"
id = "e45edcc5347e4b409169c1d0a9b2ed5d"

[[env.production.kv_namespaces]]
binding = "DISCOGS_OAUTH_CLIENTS"
id = "37c1184f1c514223b1a340e0778dd84e"

[[env.production.kv_namespaces]]
binding = "DISCOGS_OAUTH_TOKENS"
id = "45695a7b54c346219b4ed22ce5d95d07"

# Secrets (set via wrangler secret put):
# - DISCOGS_CONSUMER_KEY
# - DISCOGS_CONSUMER_SECRET
# - JWT_SECRET 